package:
  name: astra-toolbox
  version: '1.8.3'

source:
  git_url: https://github.com/paskino/astra-toolbox.git
  git_tag: numpy_versions

build:
  number: 0
  script_env:
    - CC # [linux]

test:
  imports:
    - astra
  requires:
    # To avoid large downloads just for testing after build phase
    - nomkl # [not win]
    # import scipy.sparse.linalg fails with mkl-2017.0.4 on Windows
    - mkl !=2017.0.4 # [win]

requirements:
  build:
    - python
    - cython >=0.13
    - nomkl # [not win]
    - numpy {{ numpy }}
    - scipy
    - six
    - libastra ==1.8.3
    - boost

  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - scipy
    - six
    - libastra ==1.8.3


about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
