package:
  name: libastra
  version: '1.8.3'

source:
  git_url: https://github.com/paskino/astra-toolbox.git
  git_tag: numpy_versions

build:
  number: 0
  script_env:
    - CC # [linux]
    - CXX # [linux]

requirements:
  build:
    - vs2015_runtime # [win]
    - boost 
    - boost-cpp 
    - automake 
    - autoconf 
    - libtool 
    - cudatoolkit {{ cudatoolkit }} # [linux]

  run:
    - vs2015_runtime # [win]
    - cudatoolkit {{ cudatoolkit }} # [linux]

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'
